# Generated by Django 5.2 on 2025-04-29 22:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Категория аты')),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True, verbose_name='Слаг (авто)')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категориялар',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Аты')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Сүрөттөмө')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Баасы ($)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Сүрөт')),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Рейтинг (0-5)')),
                ('discount_percentage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Скидка (%)')),
                ('discount_message', models.CharField(blank=True, max_length=100, null=True, verbose_name='Скидка билдирүүсү')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='menu.category', verbose_name='Категория')),
                ('saved_by', models.ManyToManyField(blank=True, related_name='saved_products', to=settings.AUTH_USER_MODEL, verbose_name='Кимдер сактады')),
            ],
            options={
                'verbose_name': 'Товар (Тамак)',
                'verbose_name_plural': 'Товарлар (Тамактар)',
                'ordering': ['-created_at'],
            },
        ),
    ]
