# Generated by Django 5.2 on 2025-04-29 23:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Аты')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Билдирүү')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Жөнөтүлгөн убакыт')),
                ('is_read', models.BooleanField(default=False, verbose_name='Окулду')),
            ],
            options={
                'verbose_name': 'Байланыш Билдирүүсү',
                'verbose_name_plural': 'Байланыш Билдирүүлөрү',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активдүү'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активдүү (көрүнгөн)'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Слаг (авто)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Түзүлгөн дата'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Баасы ($)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Жаңыланган дата'),
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Аталышы')),
                ('slug', models.SlugField(blank=True, max_length=270, unique=True, verbose_name='Слаг (авто)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='Сүрөт')),
                ('content', models.TextField(verbose_name='Мазмуну')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Жарыяланган датасы')),
                ('is_published', models.BooleanField(default=True, verbose_name='Жарыяланды')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Блог Барагы',
                'verbose_name_plural': 'Блог Барактары',
                'ordering': ['-publish_date'],
            },
        ),
    ]
