# Generated by Django 5.2 on 2025-04-30 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_contactmessage_category_is_active_product_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Аты')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилиясы')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон номери')),
                ('address', models.CharField(max_length=250, verbose_name='Дареги')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Почта индекси')),
                ('city', models.CharField(max_length=100, verbose_name='Шаар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Түзүлгөн убакыт')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңыланган убакыт')),
                ('paid', models.BooleanField(default=False, verbose_name='Төлөндү')),
                ('status', models.CharField(choices=[('Pending', 'Күтүүдө'), ('Processing', 'Иштетүүдө'), ('Shipped', 'Жөнөтүлдү'), ('Delivered', 'Жеткирилди'), ('Cancelled', 'Жокко чыгарылды')], default='Pending', max_length=10, verbose_name='Статус')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Колдонуучу')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказдар',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Баасы (заказ учурунда)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Саны')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='menu.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Заказ Элементи',
                'verbose_name_plural': 'Заказ Элементтери',
            },
        ),
    ]
